version: '3'

services:
  web:
    build: .
    depends_on:
      - db
    volumes:
      - .:/code
    container_name: garage-web
    ports:
      - "8030:8000"
    env_file: .env
    command: python ./src/manage.py runserver 0.0.0.0:8000
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: garage-db
    env_file: .env
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana:6.5.2
    ports:
      - 3060:3000

volumes:
  prometheus-data: