version: '3'

services:
  web:
    image: python:3.9
    depends_on:
      - db
    volumes:
      - .:/opt/garage
    container_name: garage-web
    ports:
      - "0.0.0.0:8030:8000"
    env_file: .env
    working_dir: /opt/garage
    command: /bin/bash -c 'scripts/run-server.sh'
  db:
    image: postgres:12.0-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    container_name: garage-db
    env_file: .env